name : Business Analytics

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Data Cleaning Script
        run: |
          python src/data_cleaning.py

      - name: Upload Product output files
        uses: actions/upload-artifact@v4
        with:
          name: output-files
          path: |
            data/generated_output/products_data.csv
            data/generated_output/sales_data.csv
            data/generated_output/customers_data.csv
          if-no-files-found: error

      - name: Debug - List generated files
        run: |
          echo "Listing generated_output folder..."
          ls -lh data/generated_output

      
      - name: Run Data Analyzing Script
        run: |
          python src/data_analysis.py

      - name: Upload result files
        uses: actions/upload-artifact@v4
        with: 
          name: result-files
          path: |
            Customers_Query_Results.csv
            # Sales_Query_Results.csv
            # Products_Query_Results.csv
